package com.example.routinetaskmanager.ui.theme

import androidx.compose.ui.graphics.Color

val EerieBlack = Color(0xFF212121)
val White = Color(0xFFFFFFFF)

val LightBackground = Color(0xFFFFFFFF)
val LightSurface = Color(0xFFF6F5FA)
val LightSurfaceDim = Color(0xFFE8E6F2)
val LightSurfaceBright = Color(0xFFF7F9FE)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF1F4F9)
val LightSurfaceContainer = Color(0xFFEEECF5)
val LightSurfaceContainerHigh = Color(0xFFE5E8ED)
val LightSurfaceContainerHighest = Color(0xFFF8F8F8)
val LightOnSurface = Color(0xFF212121)
val LightOnSurfaceVariant = Color(0xFF41474D)
val LightOutline = Color(0xFF71787E)
val LightOutlineVariant = Color(0xFFD7DDE9)
val LightSecondary = Color(0xFF9490AC)
val LightSecondaryContainer = Color(0xFFA3B1EE)
val LightOnSecondaryContainer = Color(0xFF00174A)
val LightTertiary = Color(0xFFEFF3A2)
val LightOnTertiary = Color(0xFF212121)
val LightTertiaryContainer = Color(0xFFCFDECB)
val LightPrimaryContainer = Color(0xFFE1E6FF)
val LightOnPrimaryContainer = Color(0xFF384956)

val DarkBackground = Color(0xFF0F1015)
val DarkOnBackground = Color(0xFFE9ECF2)
val DarkSurface = Color(0xFF181A20)
val DarkSurfaceDim = Color(0xFF121319)
val DarkSurfaceBright = Color(0xFF2B2E37)
val DarkSurfaceContainerLowest = Color(0xFF0D0E12)
val DarkSurfaceContainerLow = Color(0xFF161920)
val DarkSurfaceContainer = Color(0xFF1B1E26)
val DarkSurfaceContainerHigh = Color(0xFF222633)
val DarkSurfaceContainerHighest = Color(0xFF292D38)
val DarkOnSurface = Color(0xFFE9ECF2)
val DarkOnSurfaceVariant = Color(0xFFB7BECC)
val DarkOutline = Color(0xFF8A92A3)
val DarkOutlineVariant = Color(0xFF444C5D)
val DarkPrimary = Color(0xFF94AAE3)
val DarkOnPrimary = Color(0xFF1A2548)
val DarkPrimaryContainer = Color(0xFF3F4F7D)
val DarkOnPrimaryContainer = Color(0xFFEAF0FF)
val DarkSecondary = Color(0xFFA29CBE)
val DarkOnSecondary = Color(0xFF262237)
val DarkSecondaryContainer = Color(0xFF425282)
val DarkOnSecondaryContainer = Color(0xFFEAF0FF)
val DarkTertiary = Color(0xFFD1D983)
val DarkOnTertiary = Color(0xFF222319)
val DarkTertiaryContainer = Color(0xFF53634C)
val DarkOnTertiaryContainer = Color(0xFFEAF5E4)
val DarkInverseSurface = Color(0xFFE5E7EC)
val DarkInverseOnSurface = Color(0xFF202228)
